name = "goosehost-example"  
main = "worker.js"
compatibility_date = "2026-07-27"

[vars]
API_URL = "https://goosehost-example.goose-bai.workers.dev"
ADMIN_USER_IDS = ""

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "2edc698e7f884d6ea146cdc5ad0a74e0"

[triggers]
crons = ["*/30 * * * *"]
